### ISSUE TITLE
Several dilutions ?

### ISSUE THREAD

**Issue by vivian-salino** [nicoloabrate/ndl#1]
Hi @nicoloabrate,

I am looking with great interest at NDL. It's very inspiring! Of course, this also generates questions. In particular, I'm wondering why several dilutions are used in PURR, on that last line.
https://github.com/nicoloabrate/ndl/blob/82f2694f4bd3731bb86d95589972806531428b84/source/ProcessNDL.py#L733-L737
For deterministic approaches, I can see the point, such as dilution interpolations for multigroup self-shielding. But for producing continuous files for Monte Carlo, I can't see the purpose. Is infinite dilution not enough?

Could you enlighten me on the reason for such dilutions, please?

**Comment by nicoloabrate** [comment]
Dear Vivian,
thank you so much for pointing this out. I did not intend to add so many dilutions for generating ACE files, so this is a "bug"! Last year I used this class for generating a couple of files for a GROUPR application and I probably messed something up commiting that "_ad hoc_" version of the code.
I will fix this immediately,
Kind regards
Nicolo'

**Comment by nicoloabrate** [comment]
Fixed with commit [17d7988](https://github.com/nicoloabrate/ndl/commit/17d7988f63e75edc3dc60eee295d87eacba8207f)

**Comment by vivian-salino** [comment]
Dear Nicolo',
Thank you very much for this clarification!
Kind regards
